import os
import secrets
from cryptography.fernet import Fernet, InvalidToken
from dotenv import load_dotenv

load_dotenv(override=True)

def generate_secret_key():
    return secrets.token_hex(32)

def _clean_env(value):
    value = (value or "").strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"\"", "'"}:
        value = value[1:-1].strip()
    return value

def _get_fernet():
    key = _clean_env(os.getenv("FERNET_KEY"))
    if not key:
        raise RuntimeError("FERNET_KEY is missing. Run 'python generate_keys.py' and put the generated key in .env.")
    try:
        return Fernet(key.encode("ascii"))
    except Exception as exc:
        raise RuntimeError("FERNET_KEY is invalid. It must be the exact 44-character key generated by Fernet. Do not add quotes or extra characters.") from exc

def encrypt_value(value):
    if not value:
        return ""
    return _get_fernet().encrypt(value.encode("utf-8")).decode("utf-8")

def decrypt_value(value):
    if not value:
        return ""
    try:
        return _get_fernet().decrypt(value.encode("utf-8")).decode("utf-8")
    except InvalidToken as exc:
        raise RuntimeError("Stored encrypted value cannot be decrypted. Keep the same FERNET_KEY used when it was encrypted.") from exc

def generate_fernet_key():
    return Fernet.generate_key().decode("ascii")
